# Generated by Django 5.0 on 2024-06-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_data_updated_at_alter_user_updated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['name', 'age'], name='user_data_name_97ceb7_idx'),
        ),
    ]
