# Generated by Django 5.0 on 2024-06-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0007_skilloffer_skillrequest'),
        ('user', '0007_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skill_offer',
            field=models.ManyToManyField(related_name='offered_by', through='skill.SkillOffer', to='skill.skill'),
        ),
        migrations.AddField(
            model_name='user',
            name='skill_request',
            field=models.ManyToManyField(related_name='requested_by', through='skill.SkillRequest', to='skill.skill'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
