version: '3.8'
services:

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "81:80"
    depends_on:
      - web

  web:
    container_name: skillapp
    build:
      context: .
    ports: 
      - "8001:8000"
    depends_on:
      - db

  db: 
    container_name: postgresdb
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  

