# Generated by Django 5.0 on 2024-06-05 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_alter_skillcatogary_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcatogary',
            name='description',
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('catogary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.skillcatogary')),
            ],
        ),
    ]
