# Generated by Django 5.0 on 2024-06-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_remove_skillcatogary_description_skill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillCatogary',
            new_name='SkillCategory',
        ),
    ]
