# Generated by Django 5.0 on 2024-06-12 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0004_rename_skillcatogary_skillcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='catogary',
            new_name='category',
        ),
    ]
