# Generated by Django 5.0 on 2024-06-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0005_rename_catogary_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-06-04T15:09:11.418461+05:30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
